### ISSUE TITLE
Upload to Play Store

### ISSUE THREAD

**Issue by ErikBoesen** [amalik12/dining_plus#1]
Hey there! I know this project is not really maintained anymore and you have moved on. However, I really enjoy this app a lot more than Yale's official dining app. I would love to be given commit access and be given your permission to put this up on the Play Store. I think that could expose it to a wider audience. I would absolutely not take credit for it and would provide attribution for your work.

Let me know if you'll consider it! If you want me to make some PRs first before making me a maintainer I can do that.

**Comment by amalik12** [comment]
Hi! I'm glad to know that someone likes the app! I would definitely be up for publishing the app on the Play Store. You can go ahead and make a few PRs before I give you commit access.

**Comment by ErikBoesen** [comment]
Thanks for the opportunity! I'll find some enhancements I can make and open issues for them.

**Comment by ErikBoesen** [comment]
By the way, were you ok with me publishing the app on my own developer account for future maintainability? I totally understand, of course, if you're not comfortable with that.

**Comment by amalik12** [comment]
That's completely fine, I think you're also able to give my account access to the app in the Play Console.

**Comment by ErikBoesen** [comment]
I will do that.
