### ISSUE TITLE
Add link to Play Store in README/description

### ISSUE THREAD

**Issue by ErikBoesen** [amalik12/dining_plus#40]
https://play.google.com/store/apps/details?id=com.adisa.diningplus

11 downloads in the first couple hours!

**Comment by amalik12** [comment]
Looks great! Could you credit me as the original creator of the app in the description? Also, could you add my developer account to the app in the Google Play Console? My email's adisamalik@gmail.com.

**Comment by ErikBoesen** [comment]
Oh yeah, of course! Done!
