### ISSUE TITLE
Put titles in header

### ISSUE THREAD

**Issue by ErikBoesen** [amalik12/dining_plus#5]
In the first screenshot in the README, "Closed Now" is shown within the body content. I would like to put it in the header, in place of "Dining Plus."

**Comment by amalik12** [comment]
I'm not sure if this would work, since dining halls can also appear under a "Open now" header if they're open, like this mockup: ![](https://dl.dropboxusercontent.com/s/huye04ewxvxr36m/Photoshop_2019-06-19_22-39-02.png)

**Comment by ErikBoesen** [comment]
Oh, yeah, that's fair, I think I misunderstood the way the interface is supposed to work.
